services:
  #___Infrastructure___
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - ecommerce-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - ecommerce-network
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    networks:
      - ecommerce-network
  #___Databases___
  AuthServiceDB:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: "AuthService"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - AuthServiceDB-data:/var/lib/mysql
      - ./Back-End/AuthService/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ecommerce-network
  ProductServiceDB:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ProductsDb
      MYSQL_ROOT_PASSWORD: admin
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - ProductServiceDB-data:/var/lib/mysql
      - ./Back-End/ProductService/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ecommerce-network

  #___Micro-Services___
  AuthServiceAPI:
    build: 
      context: ./Back-End/AuthService
      dockerfile: dockerfile
    image: authservice-api:latest
    container_name: authservice-api 
    ports:
      - "5001:5181"
      #- "5002:7214"
    depends_on:
      AuthServiceDB:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:5181
        - ConnectionStrings__DefaultConnection=Server=AuthServiceDB;Port=3306;Database=AuthService;User=root;Password=admin;
        - Kafka__BootstrapServers=kafka:29092
    networks:
        - ecommerce-network
  ProductServiceAPI:
    build:
      context: ./Back-End/ProductService
      dockerfile: dockerfile
    image: productservice-api:latest
    container_name: productservice-api
    ports:
      - "5002:5252"
    depends_on:
      ProductServiceDB:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:5252
        - ConnectionStrings__DefaultConnection=Server=ProductServiceDB;Port=3306;Database=ProductsDb;User=root;Password=admin;
        - Kafka__BootstrapServers=kafka:29092
    networks:
      - ecommerce-network
volumes:
  AuthServiceDB-data: 
    driver: local
  ProductServiceDB-data:
    driver: local
networks:
  ecommerce-network:
    driver: bridge
